### ISSUE TITLE
修改资源文件导致程序被自定义化

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#102]
Description:

```json
"qwq": [
    "hjl2011 是蒟蒻。",
    "",
    "用法:",
    "",
    "无",
    "",
    "这个命令没有参数.",
    "我只是想卡一下 WCH."
]
```

Screenshot :

![image](https://user-images.githubusercontent.com/100132650/198861586-d440cdbd-de9a-4cbe-9e10-9d153059af3c.png)

Log File:

```log
[11:37:08] [INFO]: Input command array: "help", "qwq".
[11:37:08] [INFO]: Reading file "C:\Users\hjl2011\Desktop\WCH_v2.1.1-alpha.4_all\resources\zh-CN\help.json".
```

Program Version: `2.1.1-alpha.4`

Operating System Version: `Windows 10.0.22621.755`

**Comment by hjl2011** [comment]
~热烈庆祝 WCH Issue 数量达到 102！~

**Comment by ren-yc** [comment]
非紧急 Issue，将择期采用文件哈希校验 / 封装 DLL 的方式避免此类问题发生。

**Comment by ren-yc** [comment]
经过交流，暂定解决方案：

添加 Pre-build 脚本获取资源文件 Hash 值，并作为宏定义传入 MSBuild。

资源文件读取模块使用相应 Hash 算法运行时获取 Hash 值，并进行比对。
