### ISSUE TITLE
关于 `help` 命令

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#107]
### 故障描述

help 命令的语言好像有问题。

### 细节信息

![](https://user-images.githubusercontent.com/100132650/199483323-504c7bf6-2d13-4da3-a3b8-f637616fc528.png)

### 程序版本

`v2.1.1-alpha.5`

### 操作系统版本

`Windows 10.0.22621.755`

### 是否自己修复故障

否

**Comment by ren-yc** [comment]
此故障预计将随 #106 的 `restart` 命令修复。
