### ISSUE TITLE
关于右键栏

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#109]
### 特性描述

右键 `WCH` 图标时，如程序当前窗口为显示状态，功能为 `Hide, Exit`；如程序当前窗口为隐藏状态，功能为 `Show, Exit`。

### 是否自己实现特性

否

**Comment by ren-yc** [comment]
控制台为显示状态时，可输入 `hide` 隐藏该窗口。

但控制台为显示状态时，Ctrl + Down 仍有其它作用：结束 `count-down` 等。

**Comment by ren-yc** [comment]
考虑此按钮仅适用于隐藏 / 显示控制台窗口。

**Comment by ren-yc** [comment]
目前仅将该按钮的作用设为模拟按下 Ctrl + Down。
