### ISSUE TITLE
关于 `count-down` 命令

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#110]
### 故障描述

`count-down` 命令在窗口**非全屏时**显示**可能**出错。

### 细节信息

![](https://user-images.githubusercontent.com/100132650/199491735-cba11b2d-bdcd-4f25-b1f1-af5088b239ae.png)

### 程序版本

`v2.1.1-alpha.5`

### 操作系统版本

`Windows 10.0.22621.755`

### 是否自己修复故障

否

**Comment by ren-yc** [comment]
考虑执行初始化时自动设置窗口强制为全屏。

**Comment by hjl2011** [comment]
> 考虑执行初始化时自动设置窗口强制为全屏。

但黑窗口会遮挡网课。

**Comment by ren-yc** [comment]
此 Issue 的具体解决方法为：强制指定控制台窗口大小、通过消息函数忽略 `WM_SIZE` 和 `WM_SIZING` 消息以达到不能修改窗口大小的目的。

但现在我们的控制台窗口句柄不具备 `WndProc()` 函数，并且玄学 `ShowWindow()` 有时出问题，现在此 Issue 不予修复。
