### ISSUE TITLE
添加新命令 `showlog` 等

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#112]
### 特性描述

建议添加一些新命令：`showlog`（最好是打开 `Log` 文件夹）、`showtmp`（打开 `Temp/WCH` 文件夹）
因为挨个去找文件夹真的太麻烦了。

### 是否自己实现特性

否

**Comment by ren-yc** [comment]
更新日志：

添加 `develop` 命令集。

添加子命令 `develop opendata` 打开 `%USERPROFILE%\AppData\Local\WCH\` 文件夹。

添加子命令 `develop opentemp` 打开 `%USERPROFILE%\AppData\Local\Temp\WCH\` 文件夹。

**Comment by ren-yc** [comment]
附注：

临时文件夹路径迁移至 `%USERPROFILE%\AppData\Local\Temp\WCH\` 文件夹。
