### ISSUE TITLE
关于数据的创建与读取

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#113]
### 故障描述

见 Issue #108 中的[这条 Comment](https://github.com/class-tools/Web-Class-Helper/issues/108#issuecomment-1320891645)。

1. 里面有一条 `[21:55:34] [ERROR]: Data in file "***\AppData\Local\WCH\settings.json" corrupted.`，所以我去查了下 `***\AppData\Local\WCH\data`，发现里面空空如也。
2. 在我查找日志时，发现 `latest.log` 包含了很多条程序运行、程序结束信息。

终上所述，建议在打开 WCH 时自动判断。

### 细节信息

见 Issue #108 中的[这条 Comment](https://github.com/class-tools/Web-Class-Helper/issues/108#issuecomment-1320891645)。

### 程序版本

`v2.1.1-beta.2`

### 环境

操作系统版本：`10.0.22621.819`
操作系统架构：`x64`
程序架构：`x64`

顺带一提：`WCH_v2.1.1-beta.2` 是没有 `sysinfo` 命令的（

### 是否自己修复故障

否

**Comment by ren-yc** [comment]
Duplicate #108.
