### ISSUE TITLE
添加“恢复默认设置”功能

### ISSUE THREAD

**Issue by Daijianghao** [class-tools/Web-Class-Helper#123]
### 特性描述

如题，建议开发“恢复默认（出厂）设置”的功能，一次性修改所有的选项，重置设定。

- 一次性将设置(config)中的选项，全部改为默认值。
- （可选）恢复主程序文件夹下的所有文件。
- （可选）重置 `%USERPROFILE%/AppData/Local/WCH` 目录下，`clock, task, work, config` 等命令的所有运行数据。

可以方便开发测试、用户使用和误删误改后的恢复等。 

### 其它信息

如果用户想要删除所有信息、恢复默认设置或重装软件，重新来过，那么他就需要输入 `clock clear, task clear, work clear, config set` 等命令，十分麻烦。不是所有用户都能了解和运用这些清空命令的。

再退一步说，即使用户不使用清空命令，也不是所有用户都会自己去 `AppData` 里一个个删除修改的。一键化的处理显然更优。

否则，用户发现了使用上的问题（譬如用户瞎揿，读不懂英文，把提示符的 `>>>` 给改掉了，发现界面不对想重装解决），在删除主程序目录，重新下载后，发现自己设的 `clock` 闹钟列表还在，各种 `settings.json` 的设置还在，只能对着屏幕抓耳挠腮，不知道怎么解决

### 是否自己实现特性

否

**Comment by ren-yc** [comment]
👍
