### ISSUE TITLE
请求添加命令 `open`

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#124]
### 特性描述

- `open` 命令
    - [x] `open wiki`（也就是 `wiki` 命令），打开 [Wiki](https://github.com/class-tools/Web-Class-Helper/wiki)。
    - [x] `open releases`，打开程序发布界面（[Releases](https://github.com/class-tools/Web-Class-Helper/releases)）。
    - [x] `open code`，打开[主界面](https://github.com/class-tools/Web-Class-Helper/)。
    - [x] `open picfolder`，打开图片文件夹。
- 关于 `ow`、`fate` 命令，我觉得至少要声明下 API 与程序无关，不负任何责任等等。

### 是否自己实现特性

是

**Comment by ren-yc** [comment]
~~全部非必要。~~

“清空日志”不会实现。

图标不会再更改。

其余经过讨论后决定实现与否。

**Comment by Daijianghao** [comment]
说说个人的看法，仅供参考。
要是有错误可以直接改。

- （关于重启，关机，锁定等操作系统命令）与 #96 重复。可以用 Windows 系统下的“命令提示符”程序和 Windows 图形化操作等方式，简单便捷地达到同样的目的。而且谁会闲的没事开个 WCH 就为了关机。
- （添加 `sysinfo` 的硬件显示）不做评价，有用就加。但好像硬件问题对 WCH 好像没有差异（？）。
- 不同意，几乎所有主流软件都是存在 `AppData` 里而且不会询问的，不信可以自己看看自己的 `AppData` 里有多少文件夹。能修改的只有安装目录，数据目录是不会改位置的。而本项目没有安装向导，可以自由选择安装目录。
- `open` 命令。`open wiki` 是为了照顾不熟悉 Github 的用户，用来一键找到帮助的地方。其他功能我觉得都是 Github 爱好者或者开发人员需要使用的，都是熟悉 Github 的群体，可以直接在浏览器打开网页上用图形化操作打开，没有必要。
