### ISSUE TITLE
EHC Compiler compatibility

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#13]
Description:

This project cannot be compiled with GCC. So I hope this project is compatible with GCC.

![image](https://user-images.githubusercontent.com/53416099/167254221-99e92ec8-444b-4ca3-9813-15791c9cd4e7.png)

**Comment by ren-yc** [comment]
In fact, we made this decision after careful consideration with @Orlicz . Considering that our project is mainly oriented to Windows, we used MSVC at last.
