### ISSUE TITLE
BUG Input string with spaces in command "game"

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#17]
Description: I input string with spaces in command `game` and it causes this problem.

Screenshot: ![f92e782c578827990a94f8fcc39da1c2_imgpsh_fullsize_anim](https://user-images.githubusercontent.com/100132650/168004503-1a6aa311-a2ff-441b-99f2-c4e436651828.png)

Program Version: `2.0.0-beta.3`

Operating System Version: `Windows 7`

**Comment by hjl2011** [comment]
Program Version: v2.0.0_beta.3_all

Operating System Version: windows 6.1.7601

**Comment by ren-yc** [comment]
Note that Windows 7 is no longer supported with WCH.
