### ISSUE TITLE
BUG Command "game" prompt has bug

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#18]
Description: Prompt has bug.

Screenshot: ![image](https://user-images.githubusercontent.com/100132650/168010534-6cc80d63-7190-45d9-88d3-d04f395719f1.png)

Program Version: `2.0.0-beta.3`

Operating System Version: `Windows 7`

**Comment by hjl2011** [comment]
![image](https://user-images.githubusercontent.com/100132650/168015154-c6861421-95d1-4ee0-b1e9-d502cfaa3c9d.png)

**Comment by ren-yc** [comment]
The thing that causes this problem is the same as #17.
