### ISSUE TITLE
Add a new command `fate`

### ISSUE THREAD

**Issue by Daijianghao** [class-tools/Web-Class-Helper#23]
Like the title, I'm gonna to write a new command.

It support clock in every day and get the daliy fate for a new day.

**Comment by Daijianghao** [comment]
This enhancement will be added in `WCH V2.1.0`,I close it for the time being and will reopen it if needed

**Comment by Daijianghao** [comment]
Pul request is here:<https://github.com/class-tools/Web-Class-Helper/pull/24>.

If you are in consideration of the new fuction,might as well to see the program

**Comment by Daijianghao** [comment]
由于版本更新过多，此处给出独立的 `fate`  程序供合并：

<https://github.com/Daijianghao/Web-Class-Helper-fate>

**Comment by ren-yc** [comment]
Because the content in this feature contains potential copyright problems, this Issue will be closed until these problems are clear.

**Comment by ren-yc** [comment]
Already added in https://github.com/class-tools/Web-Class-Helper/commit/907cc975320b5d6477b75eb31c94460c587b10c1.
