### ISSUE TITLE
BUG Speedtest x86 炸了

### ISSUE THREAD

**Issue by ioi-ak-dajuruo888** [class-tools/Web-Class-Helper#37]
Description: 打开 Speedtest x86 时报错（见下面截图），是编译 Python 文件时有一个使用的包没有安装。

Screenshot (If any):
![](https://user-images.githubusercontent.com/95965215/170899950-03587c20-d7eb-4b48-bd4c-bf638f18910e.jpg)

Terminal Output (If needed): 无

Log File: 无

Program Version: `2.0.1-beta.1 x86 speedtest`

Operating System Version: `Windows 10`

**Comment by ioi-ak-dajuruo888** [comment]
代码没问题，是编译时少了一个包，需要重新编译

**Comment by ren-yc** [comment]
马上重新编译，感谢反馈。

**Comment by ren-yc** [comment]
已经修复，感谢反馈。

相关补丁详见 Discussions。
