### ISSUE TITLE
EHC 托盘图标

### ISSUE THREAD

**Issue by ioi-ak-dajuruo888** [class-tools/Web-Class-Helper#38]
Description: 据 [洛谷 WCH 2.0.0 广告](https://www.luogu.com.cn/discuss/441272) 显示， `2.0.1` 版本加入托盘图标，但是 `2.0.1-beta.1` 版本还未加入托盘图标，希望增加托盘图标。

Expected Effect Picture (If any):

![](https://user-images.githubusercontent.com/95965215/170909376-4c63d46b-6b77-4a87-bb87-5a002c52791f.png)

**Comment by ren-yc** [comment]
@Orlicz 大佬已经把 [模板](https://github.com/Orlicz/IconTest) 做好了，近期准备合并到主程序中。

**Comment by ren-yc** [comment]
> 催的话，就是咕掉了（

** 的我屑屑你。

**Comment by ren-yc** [comment]
~~我不行了，现征集 PR。~~

参考链接

https://github.com/class-tools/Web-Class-Helper/commit/7fa1b32edeb5b2a78c2b27fc3a2135461e81cc74

https://stackoverflow.com/questions/72433671/how-to-add-tray-icon-in-a-c-console-program

**Comment by juruo888** [comment]
> 催的话，就是咕掉了（

**的我谢谢你啊 [恼]
![](https://user-images.githubusercontent.com/106530969/171335781-d386edfa-abb9-494c-9ef4-8275c25f238f.png)

**Comment by ren-yc** [comment]
我们已经编写完毕相关的重要核心模块，当前效果如下：

![image](https://user-images.githubusercontent.com/53416099/171783775-47c5764c-a80b-42ca-b23a-2e38cba3b385.png)

待完全内测完毕后将会发布公测版本。

感谢您的 ~~催促~~ 提醒！
