### ISSUE TITLE
BUG 支持中文后的多个命令故障

### ISSUE THREAD

**Issue by Daijianghao** [class-tools/Web-Class-Helper#47]
- [x]  `anti-idle` 在按下 `Ctrl+Down` 后无法リカバリ。
- [x] 使用 `ow` 会出现乱码。
- [x] `work` 无法 `delete`。
- [x] 使用 `quit` 后无法保存，需要使用 `save` 才能保存，建议使用 `quit` 相当于“保存+終了”。

**Comment by juruo888** [comment]
对于 Task 4，这是之前特意这么做的

详情请见 #30 及 https://githubfast.com/class-tools/Web-Class-Helper/issues/30#issuecomment-1140165225

**Comment by Daijianghao** [comment]
> 对于 Task 4，这是之前特意这么做的
> 
> 详情请见 #30

有点麻烦，不知道的使用者可能设了一大堆 `task,work,clock` 然后自然 `quit` 发现没保存。

那这样的话，`quit` 命令就等于 叉叉 了，不保存可以叉叉关，保存 `quit` 关分工明确。

**Comment by juruo888** [comment]
> > 对于 Task 4，这是之前特意这么做的
> > 详情请见 #30
> 
> 有点麻烦，不知道的使用者可能设了一大堆 `task,work,clock` 然后自然 `quit` 发现没保存。
> 
> 那这样的话，`quit` 命令就等于 叉叉 了，不保存可以叉叉关，保存 `quit` 关分工明确。

但是本来是想 叉叉=quit 的，然后检测按叉叉有某些问题，就 quit 不保存，save 保存了

而且使用者使用前应该查看 Wiki 或使用 help 命令，看了就不会直接 quit 关了

**Comment by ren-yc** [comment]
对于 Task 4，另一种可行的方案是实时修改数据文件。

**Comment by juruo888** [comment]
> 对于 Task 4，另一种可行的方案是实时修改数据文件。

正确的。

但是实时修改数据文件可能会造成低配电脑卡顿，因此可以使用完一个命令添加一堆东西之后再保存，具体实现可以前两次使用该命令添加时计时，后面如果再计时时间过了这个时间+5 秒就保存。

**Comment by hjl2011** [comment]
> > 对于 Task 4，另一种可行的方案是实时修改数据文件。
> 
> 正确的。
> 
> 但是实时修改数据文件可能会造成低配电脑卡顿，因此可以使用完一个命令添加一堆东西之后再保存，具体实现可以前两次使用该命令添加时计时，后面如果再计时时间过了这个时间+5 秒就保存。

> 造成低配电脑卡顿

实测低配电脑不会卡顿

**Comment by juruo888** [comment]
> > > 对于 Task 4，另一种可行的方案是实时修改数据文件。
> > 
> > 
> > 正确的。
> > 但是实时修改数据文件可能会造成低配电脑卡顿，因此可以使用完一个命令添加一堆东西之后再保存，具体实现可以前两次使用该命令添加时计时，后面如果再计时时间过了这个时间+5 秒就保存。
> 
> > 造成低配电脑卡顿
> 
> 实测低配电脑不会卡顿
> 
> > 后面如果再计时时间过了这个时间+5 秒就保存。
> 
> 这个好像很复杂吧，而且貌似解决不了 `Task 4` 吧
> 
> @juruo888

如果不卡的话可以提供一个设置入口，用来设置是否自动保存，也可以设两种模式，有更改立即保存，和过特定时间有更改保存，第二种再设置保存时长

**Comment by juruo888** [comment]
> * [x]   `anti-idle` 在按下 `Ctrl+Down` 后无法リカバリ。
> * [ ]  使用 `ow` 会出现乱码。
> * [ ]  `work` 无法 `delete`。
> * [ ]  使用 `quit` 后无法保存，需要使用 `save` 才能保存，建议使用 `quit` 相当于“保存+終了”。

リカバリ 草

**Comment by ren-yc** [comment]
Task 4 由于重要性权重较小，将优先修复 / 添加权重较高的特性。

若出现较大且由此造成的 Bug，将予以修复。
