### ISSUE TITLE
BUG ow 命令末尾有问号

### ISSUE THREAD

**Issue by Daijianghao** [class-tools/Web-Class-Helper#56]
如题，当我在使用 WCH 的 `ow` 命令时，我发现几乎每个随机句后都有一个半角问号，且不像是随机句本身的问号。

猜测是编码问题。

[![XoKaqg.png](https://s1.ax1x.com/2022/06/15/XoKaqg.png)](https://imgtu.com/i/XoKaqg)

log 截图：

[![XoMFOS.png](https://s1.ax1x.com/2022/06/15/XoMFOS.png)](https://imgtu.com/i/XoMFOS)

使用环境：

Web Class Helper v2.0.1 alpha.11。

Window10，64 位。

**Comment by ren-yc** [comment]
经排查末尾 `?` 为宽字符转窄字符进行 UTF-8 与 ANSI 处理时将末尾字符转换而成。

目前已经将文件读取方式从 `wifstream` 改为 `ifstream``` 暂时性地解决了此问题。

后续将进一步确认转换核心函数是否存在漏洞（目前没有发现其他使用此函数的命令出现问题）。
