### ISSUE TITLE
BUG 好 speedtest 也炸了

### ISSUE THREAD

**Issue by juruo888** [class-tools/Web-Class-Helper#57]
Description: 好 speedtest 不只是 Win7 炸了，Win10/Win11 也炸了。推测是虚拟机没有叫 以太网 或 WLAN 的网络(?)，应该是和之前 Win7 出问题是一样的。

Screenshot (If any):
![image](https://user-images.githubusercontent.com/106530969/173730594-241435c2-e901-49cf-8dab-a99bbe4c4a43.png)

Program Version: `2.0.1-rc.1`

Operating System Version: `Windows 11 虚拟机`

**Comment by juruo888** [comment]
虚拟机会出问题，实体机不会

**Comment by ren-yc** [comment]
再次强调，`SPEEDTEST``` 将不会在重写之前修复。
