### ISSUE TITLE
BUG Windows 7 有时运行错误

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#69]
Description:

- [ ] ERR-22 + Runtime-Err : 35%
- [ ] Runtime-Err : 20%
- [ ] ERR-22 : 40%

（OK : 5%）

Screenshot :

![image](https://user-images.githubusercontent.com/100132650/176195193-03b6050e-8d0c-42f4-8fed-e8c995d64acc.png)

![image](https://user-images.githubusercontent.com/100132650/176196621-f92aa4ea-0579-4077-aa67-ad95649bdb09.png)

Log File:

```plain
[21:55:21] [INFO]: Starting "Web Class Helper 2.0.1 Public Preview (x64)".
[21:55:25] [INFO]: "CONSOLE" argument "STATUS" was set to "SHOW".
[21:56:01] [ERROR]: Signal 22 detected (Program aborted).
[21:56:02] [INFO]: "CONSOLE" argument "STATUS" was set to "HIDE".
```

Program Version: `2.0.1`

Operating System Version: `Windows 7`

**Comment by ren-yc** [comment]
请您告知我们您在错误发生后的目录结构以及相关数据文件内容（`settings.json`、`data/*.json` 等）。

**Comment by Daijianghao** [comment]
可能跟操作系统有关系，`Windows 7` 总是会出现奇奇怪怪的错误。

**Comment by hjl2011** [comment]
> 请您告知我们您在错误发生后的目录结构以及相关数据文件内容（`settings.json`、`data/*.json` 等）。

`settings.json`：

```json
{
	"Start" : "20220628215656"
}
```

目录结构：

```plain
*
|--- data
|
|--- logs
| -----> 20220628214646.log
| -----> 20220628214700.log
| -----> 20220628214816.log
| -----> 20220628214917.log
| -----> 20220628215148.log
| -----> 20220628215445.log
| -----> 20220628215521.log
| -----> 20220628215647.log
| -----> latest.log
|
|--- resources
| ------ help
| ------ website
|
| > LICENSE
| > README.md
| > README.zh-Hans.md
| > settings.json
| > WCH.ico
| > WCH32.exe
| > WCH64.exe
```

（`data` 里什么也没有qwq）

**Comment by hjl2011** [comment]
> 可能跟操作系统有关系，`Windows 7` 总是会出现奇奇怪怪的错误。

雀食qwq

**Comment by ren-yc** [comment]
目前原因不明，待完整测试后再就此 Issue 进行反馈。

**Comment by hjl2011** [comment]
> 目前发现问题：点 `X` 退出时会卡顿一会，然后才关闭窗口，卡顿时无法对窗口进行操作。
> 
> 启动时运行时错误及使用 `quit` 退出的问题未发现。

~~closed juruo888 as not planned 得了（恼~~

**有概率**，但很小（

**Comment by juruo888** [comment]
> > 目前发现问题：点 `X` 退出时会卡顿一会，然后才关闭窗口，卡顿时无法对窗口进行操作。
> > 启动时运行时错误及使用 `quit` 退出的问题未发现。
> 
> ~closed juruo888 as not planned 得了（恼~
> 
> **有概率**，但很小（

这边测试结果是每次点 `X` 都会卡顿

**Comment by hjl2011** [comment]
> > > 目前发现问题：点 `X` 退出时会卡顿一会，然后才关闭窗口，卡顿时无法对窗口进行操作。
> > > 启动时运行时错误及使用 `quit` 退出的问题未发现。
> > 
> > 
> > ~closed juruo888 as not planned 得了（恼~
> > **有概率**，但很小（
> 
> 这边测试结果是每次点 `X` 都会卡顿

这边的结果是卡顿+RE 。。。

**Comment by juruo888** [comment]
RC 3 在 Win7 的测试结果表明启动时不会出现 RE

**Comment by ren-yc** [comment]
由于此问题包含潜在的 Windows 系统 API 问题，将在得到解决方案后再对项目进行修改。

目前暂不予处理。

欢迎提供更多信息。

**Comment by hjl2011** [comment]
对不起，点错了/kk

**Comment by ren-yc** [comment]
我们在 `SECURITY.md` 中划分了受支持和不受支持的 Windows 操作系统版本。

Windows 7（6.1.x.x）目前暂不确定，但绝大多数功能均无法使用。

**Comment by hjl2011** [comment]
ok qwq

**Comment by hjl2011** [comment]
还真就暂不确定（

~又双叒叕好了~
