### ISSUE TITLE
EHC 可自定义截图保存路径

### ISSUE THREAD

**Issue by Daijianghao** [class-tools/Web-Class-Helper#70]
建议可在设置中设置 `pi` 命令的图片保存路径，这样会方便很多。

比如每天网课的笔记都一个个文件夹分开，看到笔记截下图，可以不用后期在费精力整理&拷贝。

**Comment by juruo888** [comment]
~~无意义举报了~~

你貌似是手滑发了这个，我帮你 Close as not planned 了

**Comment by Daijianghao** [comment]
> ~无意义举报了~
> 
> 你貌似是手滑发了这个，我帮你 Close as not planned 了

还 没 写 完，刚差点电脑被收了

**Comment by juruo888** [comment]
**个人感觉** 在 2.2.0 的自定义设置可能会加

**Comment by ren-yc** [comment]
在自定义设置更新前暂时不会添加。
