### ISSUE TITLE
EHC `anti-idle` 退出前提示

### ISSUE THREAD

**Issue by Daijianghao** [class-tools/Web-Class-Helper#71]
Description:

如题，一个 `Ctrl+Down` 或托盘点一下，就可以退出，就可以在网课的时候上网冲浪，让犯错的成本为零。

建议退出 `anti-idle` 前增加提示和鸡汤，如：

`你确定要退出“专注模式”吗(Y/N)`

`业精于勤，荒于嬉；行成于思，毁于随。 --韩愈`

---

也可以自定义退出前提示，可放置于 `settings.json` 内，如：

（自定义）：`颓你【】颓，再颓你就没了。`

自定义鸡汤，比如我自己写的[（垃圾）网页](https://daijianghao.github.io/advise-study-html/)。

Expected Effect Picture (If any):

+ 按下 `Ctrl+Down/托盘` 时，弹出自己窗口。
+ 去 `settings.json` 里取自定义鸡汤，随后询问是否退出专注模式。
+ 确认退出：恢复任务栏。
+ 不退出：隐藏自己。

**Comment by ren-yc** [comment]
~~个人感觉如果加了这个东西某些人可能还会点击“否”（大雾）确认退出这个模式吧。~~

**Comment by ren-yc** [comment]
~~个人感觉如果加了这个东西某些人可能还会点击“否”（大雾）确认退出这个模式吧。~~

**Comment by Daijianghao** [comment]
> 

~那人硬要退出咱也拦不住，但是大多数人要坚持的人，在看到这个之后还是会凉心发现的吧。~

**Comment by ren-yc** [comment]
目前暂无此计划，将在多语言更新及自定义设置更新后再考虑。
