### ISSUE TITLE
EHC `count-down` 结束后响一声

### ISSUE THREAD

**Issue by juruo888** [class-tools/Web-Class-Helper#75]
Description: 倒计时结束后可以和闹钟一样响一声

Expected Effect Picture (If any): 无

**Comment by ren-yc** [comment]
将会加入。

**Comment by Daijianghao** [comment]
感觉会被吓死，尤其是我这种喜欢小窗水视频的。（

**Comment by juruo888** [comment]
> 感觉会被吓死，尤其是我这种喜欢小窗无声水视频的。（

所以闹钟也有声音啊

**Comment by ren-yc** [comment]
可能会随播放 ~~阴~~ 音乐特性加入。

**Comment by ren-yc** [comment]
目前就先 Alarm 一下。

“设置”更新将此更改为可选功能。

“音乐播放”更新可自定义播放音乐。
