### ISSUE TITLE
BUG ow 输出为空

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#76]
Description:

ow 输出为空。

Screenshot :

![](https://user-images.githubusercontent.com/100132650/179751701-1226c91d-625a-44f9-b503-7bcd9fbcca2a.png)

Log File:

```plain
[20:35:33] [INFO]: Using command: "ow".
```

Program Version: `2.1.0-alpha.1`

Operating System Version: `Windows 7`

**Comment by juruo888** [comment]
没有网络时 `ow` 会输出空，请检查网络连接。

**Comment by ren-yc** [comment]
确有此问题。

即将修复。

**Comment by ren-yc** [comment]
请注意：我们及其不推荐使用 Windows 6.1 以及下的操作系统，若出现仅在该平台上的问题，不予修复。

**Comment by hjl2011** [comment]
> 没有网络时 `ow` 会输出空，请检查网络连接。

@juruo888 有网络
