### ISSUE TITLE
忽略命令中的多余空格

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#79]
### 特性描述

![](https://user-images.githubusercontent.com/100132650/187398599-cb9869f2-fa02-4781-9d3e-4717d0ae3e90.png)

期望：`LICENSE` 命令正常执行。

### 是否自己实现特性

是

**Comment by hjl2011** [comment]
其他：
前面空白的字符为空格（`[space]`）

**Comment by ren-yc** [comment]
征集 PR。
