### ISSUE TITLE
EHC new command

### ISSUE THREAD

**Issue by hjl2011** [class-tools/Web-Class-Helper#87]
希望可以搞一个网站屏蔽功能，例如：

```hosts
127.0.0.1        xxx # Web Class Helper
```

**Comment by ren-yc** [comment]
@class-tools/developing

我认为此功能涉及到 DNS 或驱动相关的问题，能力不足无法实现，请见谅。

**Comment by hjl2011** [comment]
> @class-tools/developing
> 
> 我认为此功能涉及到 DNS 或驱动相关的问题，能力不足无法实现，请见谅。

@ren-yc 好像直接写入 `hosts` 文件就行吧qwq
